export const DUMMY_PROJECTS = [
  {
    id: 1,
    projectName: "CRM System",
    projectCode: "CRM2024",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    pm: "John Doe",
    qa: "Jane Smith",
    technicalLead: ["Alice Johnson", "Bob Wilson"],
    ba: ["Charlie Brown", "Diana Prince"],
    developers: ["Eva Green", "Frank Miller", "Grace Lee"],
    testers: ["Henry Ford", "Iris West"],
    technicalConsultancy: ["Jack Ryan", "Kate Bishop"],
  },
  {
    id: 2,
    projectName: "E-commerce Platform",
    projectCode: "ECOM2024",
    startDate: "2024-02-01",
    endDate: "2024-11-30",
    pm: "Sarah Connor",
    qa: "Bruce Wayne",
    technicalLead: ["Clark Kent", "Diana Prince"],
    ba: ["Tony Stark", "Natasha Romanoff"],
    developers: ["Steve Rogers", "Thor Odinson", "Wanda Maximoff"],
    testers: ["Scott Lang", "Peter Parker"],
    technicalConsultancy: ["Nick Fury", "Maria Hill"],
  },
  {
    id: 3,
    projectName: "Healthcare System",
    projectCode: "HEALTH2024",
    startDate: "2024-03-01",
    endDate: "2024-12-15",
    pm: "Gregory House",
    qa: "Lisa Cuddy",
    technicalLead: ["Robert Chase", "Eric Foreman"],
    ba: ["Allison Cameron", "James Wilson"],
    developers: ["Hugh Laurie", "Olivia Wilde", "Jesse Spencer"],
    testers: ["Omar Epps", "Jennifer Morrison"],
    technicalConsultancy: ["Leonard McCoy", "Beverly Crusher"],
  },
  {
    id: 4,
    projectName: "Banking App",
    projectCode: "BANK2024",
    startDate: "2024-04-10",
    endDate: "2025-03-01",
    pm: "Walter White",
    qa: "Jesse Pinkman",
    technicalLead: ["Saul Goodman", "Hank Schrader"],
    ba: ["Skyler White", "Marie Schrader"],
    developers: ["Mike Ehrmantraut", "Gus Fring", "Tuco Salamanca"],
    testers: ["Lydia Rodarte", "Todd Alquist"],
    technicalConsultancy: ["Chuck McGill", "Kim Wexler"],
  },
  {
    id: 5,
    projectName: "Social Media App",
    projectCode: "SOCIAL2024",
    startDate: "2024-05-05",
    endDate: "2025-04-20",
    pm: "Mark Zuckerberg",
    qa: "Sheryl Sandberg",
    technicalLead: ["Elon Musk", "Tim Cook"],
    ba: ["Bill Gates", "Jeff Bezos"],
    developers: ["Steve Jobs", "Larry Page", "Sergey Brin"],
    testers: ["Sundar Pichai", "Jack Dorsey"],
    technicalConsultancy: ["Satya Nadella", "Reed Hastings"],
  },
  {
    id: 6,
    projectName: "AI Chatbot",
    projectCode: "AI2024",
    startDate: "2024-06-01",
    endDate: "2025-05-30",
    pm: "Alan Turing",
    qa: "Ada Lovelace",
    technicalLead: ["Claude Shannon", "John McCarthy"],
    ba: ["Marvin Minsky", "Geoffrey Hinton"],
    developers: ["Yann LeCun", "Andrew Ng", "Demis Hassabis"],
    testers: ["Fei-Fei Li", "Ian Goodfellow"],
    technicalConsultancy: ["Stuart Russell", "Peter Norvig"],
  },
  {
    id: 7,
    projectName: "Online Learning Platform",
    projectCode: "EDU2024",
    startDate: "2024-07-15",
    endDate: "2025-06-30",
    pm: "Khan Academy",
    qa: "Salman Khan",
    technicalLead: ["Richard Feynman", "Neil deGrasse Tyson"],
    ba: ["Stephen Hawking", "Carl Sagan"],
    developers: ["Brian Cox", "Michio Kaku", "Lisa Randall"],
    testers: ["Roger Penrose", "Max Tegmark"],
    technicalConsultancy: ["Edward Witten", "Leonard Susskind"],
  },
];

export const DUMMY_STAFFS = [
  {
    id: 1,
    staffName: "John Doe",
    department: "IT",
    jobRank: "Senior Developer",
    salary: 80000,
  },
  {
    id: 2,
    staffName: "Jane Smith",
    department: "HR",
    jobRank: "HR Manager",
    salary: 70000,
  },
  {
    id: 3,
    staffName: "Alice Johnson",
    department: "Finance",
    jobRank: "Accountant",
    salary: 65000,
  },
  {
    id: 4,
    staffName: "Bob Wilson",
    department: "Marketing",
    jobRank: "Marketing Specialist",
    salary: 60000,
  },
  {
    id: 5,
    staffName: "Charlie Brown",
    department: "IT",
    jobRank: "Software Engineer",
    salary: 75000,
  },
  {
    id: 6,
    staffName: "Diana Prince",
    department: "Sales",
    jobRank: "Sales Manager",
    salary: 72000,
  },
  {
    id: 7,
    staffName: "Eva Green",
    department: "IT",
    jobRank: "Frontend Developer",
    salary: 70000,
  },
  {
    id: 8,
    staffName: "Frank Miller",
    department: "Finance",
    jobRank: "Financial Analyst",
    salary: 67000,
  },
  {
    id: 9,
    staffName: "Grace Lee",
    department: "Marketing",
    jobRank: "SEO Specialist",
    salary: 62000,
  },
  {
    id: 10,
    staffName: "Henry Ford",
    department: "Operations",
    jobRank: "Operations Manager",
    salary: 80000,
  },
  {
    id: 11,
    staffName: "Iris West",
    department: "HR",
    jobRank: "Recruiter",
    salary: 68000,
  },
  {
    id: 12,
    staffName: "Jack Ryan",
    department: "IT",
    jobRank: "Backend Developer",
    salary: 73000,
  },
  {
    id: 13,
    staffName: "Kate Bishop",
    department: "Sales",
    jobRank: "Sales Executive",
    salary: 71000,
  },
  {
    id: 14,
    staffName: "Leo Messi",
    department: "Sports",
    jobRank: "Athlete",
    salary: 90000,
  },
  {
    id: 15,
    staffName: "Maria Hill",
    department: "Security",
    jobRank: "Security Analyst",
    salary: 78000,
  },
  {
    id: 16,
    staffName: "Nick Fury",
    department: "Security",
    jobRank: "Chief Security Officer",
    salary: 85000,
  },
  {
    id: 17,
    staffName: "Olivia Wilde",
    department: "IT",
    jobRank: "UI/UX Designer",
    salary: 69000,
  },
  {
    id: 18,
    staffName: "Paul Rudd",
    department: "Entertainment",
    jobRank: "Actor",
    salary: 95000,
  },
  {
    id: 19,
    staffName: "Quentin Tarantino",
    department: "Entertainment",
    jobRank: "Director",
    salary: 99000,
  },
  {
    id: 20,
    staffName: "Rachel Green",
    department: "Retail",
    jobRank: "Store Manager",
    salary: 70000,
  },
  {
    id: 21,
    staffName: "Steve Rogers",
    department: "Security",
    jobRank: "Captain",
    salary: 88000,
  },
  {
    id: 22,
    staffName: "Tony Stark",
    department: "R&D",
    jobRank: "Lead Engineer",
    salary: 120000,
  },
  {
    id: 23,
    staffName: "Ursula Buffay",
    department: "HR",
    jobRank: "HR Assistant",
    salary: 65000,
  },
  {
    id: 24,
    staffName: "Victor Hugo",
    department: "Publishing",
    jobRank: "Writer",
    salary: 78000,
  },
  {
    id: 25,
    staffName: "Wanda Maximoff",
    department: "R&D",
    jobRank: "Quantum Researcher",
    salary: 99000,
  },
  {
    id: 26,
    staffName: "Xavier Woods",
    department: "Sports",
    jobRank: "Coach",
    salary: 85000,
  },
  {
    id: 27,
    staffName: "Yvonne Strahovski",
    department: "Entertainment",
    jobRank: "Actress",
    salary: 98000,
  },
  {
    id: 28,
    staffName: "Zack Snyder",
    department: "Entertainment",
    jobRank: "Film Director",
    salary: 105000,
  },
  {
    id: 29,
    staffName: "Aaron Taylor",
    department: "IT",
    jobRank: "Fullstack Developer",
    salary: 77000,
  },
  {
    id: 30,
    staffName: "Bruce Wayne",
    department: "Management",
    jobRank: "CEO",
    salary: 150000,
  },
];
